language: python
python:
  - "3.6"
# command to install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -yqq software-properties-common git
  - sudo apt-get install -yqq libopenblas-dev liblapack3 python3-numpy python3-dev swig
  - sudo ln -s /usr/lib/libopenblas.so /usr/lib/libopenblas.so.3
install:
  - pip install -qqq https://download.pytorch.org/whl/cu100/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl
  - pip install -qqq numpy
  - pip install -qqq visdom
  - pip install -qqq pyflann3
# command to run tests
script:
  - pytest ./test